### ISSUE TITLE
Cannot install on Debian 9

### ISSUE THREAD

**Issue by sisyphosloughs** [ansemjo/imapfetch#4]
Hi, when I try to install via the suggestet pip method or `python setup.py` I get this error message:
```
~/sources/imapfetch$ python setup.py
  File "setup.py", line 15
    github = f"https://github.com/ansemjo/{name}"
                                                ^
SyntaxError: invalid syntax
```
My python version
```
python -V
Python 3.5.3
```

Any suggestions how to fix this on Debian 9?

**Comment by ansemjo** [comment]
Oh shoot, this is due to my extensive use of [f-Strings](https://www.python.org/dev/peps/pep-0498/) throughout the project. I *thought* they were available in Python 3.5 but it appears they were only introduced in Python 3.6.

I'll check if I can replace all string interpolation with older syntax and if that's the only blocker for Python 3.5 compatability.

**Comment by ansemjo** [comment]
Try again please. I replaced all f-string interpolation with `.format()`s.

**Comment by ansemjo** [comment]
Wait, I just tested this with Python 3.5 in a container and it does not have the `blake2b` algorithm in hashlib ... Blake2b is used to hash the header during indexing ...

**Comment by ansemjo** [comment]
I've added a workaround for the missing `blake2b` import in 34f0a0c.

You'll need to install `pyblake2` if you're running on Python 3.5:

    pip install pyblake2

**Comment by sisyphosloughs** [comment]
Thank you for the that. Pip setup works now with Python 3.5.3, but the imapfetch command is not found. Can you give me any hint where I can find the excecutable?

**Comment by ansemjo** [comment]
If you installed with `pip install --user ...` it should be in `~/.local/bin/`?

**Comment by sisyphosloughs** [comment]
Hi @ansemjo ,
thank you for your fast replay. Your fix will help me a lot.
And, yes, the executable is in ~/.local/bin/. It is strange, that the all the python setups did not put the path into a variable by default... I guess this should be done by Debian. I'll put that manually into my .bashrc.
I also installed it without --user option, because I'm not sure yet, which user account will perform the backup. Can you tell me where pip should install the system wide executables?
Thanks again!

**Comment by ansemjo** [comment]
The system-wide script installations should be in `/usr/local/bin/` but I can't find any specification that says so. There also appears to be no way to query this path dynamically (e.g. for Go you can do `go env GOPATH` etc.).

So yeah. Debian should have added that path to your `PATH` variable. Otherwise just add it in your `.bashrc` like you did before.

**Comment by sisyphosloughs** [comment]
Thx!
